#!/bin/bash
#
# Author : Vikram Khatri
#
# Purpose: Generate SSH keys
#

set +x

if ! rpm -qa | grep sshpass 2>&1 > /dev/null; then
   echo Package sshpass not found. Installing ...
   yum -y install sshpass
fi

if [ $# -lt 1 ] ; then
    echo "Usage: $0 inventoryFile"
    echo "Inventory file must have IP address, FQDN, Short Name and Password"
    echo "Inventory file parameters are space delimited"
    exit 1
fi

INVFILE=$1
BINVFILE=$(basename $INVFILE)
SKIP=${2:-false}
KNOWN_HOSTS=/tmp/known_hosts
OPTIONS="-o StrictHostKeyChecking=no"

touch $KNOWN_HOSTS
> $KNOWN_HOSTS
echo ========================================================
i=0
echo Generate hosts keys
while read IPADDR LNAME SNAME PWD
do
  ipaddr[$i]=$IPADDR
  lname[$i]=$LNAME
  sname[$i]=$SNAME
  pwd[$i]=$PWD
  ((i++))
  if ! $SKIP ; then
    ssh-keyscan -t rsa $IPADDR,$LNAME,$SNAME >> $KNOWN_HOSTS 2>/dev/null
  fi
  echo $PWD > /tmp/${USER}.$SNAME.kxy
done < $INVFILE

IPHOST=$(echo $SSH_CONNECTION | awk '{print $3}')
echo "Current IP Addr : " $IPHOST
echo "ip list         : " ${ipaddr[@]}
echo "long name list  : " ${lname[@]}
echo "short name list : " ${sname[@]}

echo ========================================================
for ((i = 0; i < ${#ipaddr[@]}; ++i));
do
  ipaddress=${ipaddr[$i]}
  longname=${lname[$i]}
  shortname=${sname[$i]}
  password=${pwd[$i]}

  if ! /usr/bin/sshpass -f /tmp/${USER}.${shortname}.kxy /usr/bin/ssh $OPTIONS $ipaddress stat ~/.ssh/id_rsa > /dev/null 2>&1; then
     echo Generating ssh keys at $shortname
     /usr/bin/sshpass -f /tmp/${USER}.${shortname}.kxy /usr/bin/ssh $OPTIONS $ipaddress ssh-keygen -t rsa -N \'\' -f ~/.ssh/id_rsa
  fi
  echo Run ssh-copy-id : copy key $IPHOST to $shortname
  /usr/bin/sshpass -f /tmp/${USER}.${shortname}.kxy ssh-copy-id -i ~/.ssh/id_rsa $OPTIONS $ipaddress
  if ! $SKIP; then
    /bin/scp $OPTIONS $KNOWN_HOSTS $ipaddress:~/.ssh
    /bin/scp $OPTIONS genSSH $ipaddress:/tmp
    /bin/scp $OPTIONS $INVFILE $ipaddress:/tmp
  fi
done
/bin/rm -f $KNOWN_HOSTS


if ! $SKIP ; then
  for ((i = 1; i < ${#ipaddr[@]}; ++i));
  do
    ipaddress=${ipaddr[$i]}
    shortname=${sname[$i]}
    password=${pwd[$i]}

    echo Run Remote ssh-copy-id : copy key from $IPHOST to $shortname
    /usr/bin/ssh $OPTIONS $ipaddress "/tmp/genSSH /tmp/$BINVFILE true"
  done

  for ((i = 0; i < ${#ipaddr[@]}; ++i));
  do
    ipaddress=${ipaddr[$i]}
    /usr/bin/ssh $OPTIONS $ipaddress "/bin/rm -f /tmp/${USER}.${shortname}.kxy"
    /usr/bin/ssh $OPTIONS $ipaddress "/bin/rm -f /tmp/$BINVFILE"
  done
fi
