#!/usr/bin/expect

set timeout 20

set cmd [lrange $argv 1 end]
set password [lindex $argv 0]

eval spawn $cmd
expect {
"(yes/no)?"     {
        send -- "yes\r"
        exp_continue
        }
"*password:*" {
        send -- "$password\r"
        exp_continue
        }
eof
}
exit
